export const navItems = [
  { label: 'All-Time Table', path: '/all-time-table', icon: 'mdi-table-large' },
  { label: 'Most Wins', path: '/most-wins', icon: 'mdi-chart-bar' },
  { label: 'Data Quality', path: '/data-quality', icon: 'mdi-shield-check' },
  { label: 'Attendances', path: '/attendances', icon: 'mdi-stadium' },
  { label: 'Five-Game Streaks', path: '/five-game-streaks', icon: 'mdi-run-fast' },
  { label: 'Big Win Streaks', path: '/big-win-streaks', icon: 'mdi-format-list-numbered' },
  { label: 'Longest Gap Between Wins', path: '/longest-winless-gaps', icon: 'mdi-timer-sand' },
  { label: 'Most Chaotic Matches', path: '/most-chaotic-matches', icon: 'mdi-fire' },
  { label: 'One-Nil Wins', path: '/one-nil-wins', icon: 'mdi-numeric-1-box-outline' },
  { label: 'Longest No-Win Streaks After HT Lead', path: '/ht-lead-no-win-streaks', icon: 'mdi-flag-checkered' },
  { label: 'Comeback Kings', path: '/comeback-kings', icon: 'mdi-trophy-outline' },
  { label: 'Most Comebacks in a Season', path: '/most-comebacks', icon: 'mdi-trophy-variant-outline' },
  { label: 'Most Manager Wins', path: '/manager-wins', icon: 'mdi-whistle-outline' },
  { label: 'Manager Timeline', path: '/manager-timeline', icon: 'mdi-chart-gantt' },
  { label: 'Arsène Wenger', path: '/wenger', icon: 'mdi-account-tie-outline' },
  { label: 'Alex Ferguson', path: '/ferguson', icon: 'mdi-account-tie-outline' },
  { label: 'David Moyes', path: '/moyes', icon: 'mdi-account-tie-outline' },
  { label: 'Pep Guardiola', path: '/guardiola', icon: 'mdi-account-tie-outline' },
  { label: 'Harry Redknapp', path: '/redknapp', icon: 'mdi-account-tie-outline' },
  { label: 'José Mourinho', path: '/mourinho', icon: 'mdi-account-tie-outline' },
  { label: 'Jürgen Klopp', path: '/klopp', icon: 'mdi-account-tie-outline' },
  { label: 'Sam Allardyce', path: '/allardyce', icon: 'mdi-account-tie-outline' },
  { label: 'Rafael Benítez', path: '/benitez', icon: 'mdi-account-tie-outline' },
  { label: 'Mark Hughes', path: '/hughes', icon: 'mdi-account-tie-outline' },
  { label: 'Mauricio Pochettino', path: '/pochettino', icon: 'mdi-account-tie-outline' },
  { label: 'Mikel Arteta', path: '/arteta', icon: 'mdi-account-tie-outline' },
  { label: 'Eddie Howe', path: '/howe', icon: 'mdi-account-tie-outline' },
  { label: 'Brendan Rodgers', path: '/rodgers', icon: 'mdi-account-tie-outline' },
  { label: 'Roy Hodgson', path: '/hodgson', icon: 'mdi-account-tie-outline' },
  { label: 'Steve Bruce', path: '/bruce', icon: 'mdi-account-tie-outline' },
  { label: "Martin O'Neill", path: '/o-neill', icon: 'mdi-account-tie-outline' },
  { label: 'Kevin Keegan', path: '/keegan', icon: 'mdi-account-tie-outline' },
  { label: 'Kenny Dalglish', path: '/dalglish', icon: 'mdi-account-tie-outline' },
  { label: "David O'Leary", path: '/o-leary', icon: 'mdi-account-tie-outline' },
  { label: 'Arsenal', path: '/arsenal', icon: 'mdi-shield-outline' },
  { label: 'Manchester United', path: '/manchester-united', icon: 'mdi-shield-outline' },
  { label: 'Liverpool', path: '/liverpool', icon: 'mdi-shield-outline' },
  { label: 'Tottenham Hotspur', path: '/tottenham', icon: 'mdi-shield-outline' },
  { label: 'West Ham United', path: '/west-ham', icon: 'mdi-shield-outline' },
  { label: 'Manchester City', path: '/manchester-city', icon: 'mdi-shield-outline' },
  { label: 'Newcastle United', path: '/newcastle', icon: 'mdi-shield-outline' },
  { label: 'Sunderland', path: '/sunderland', icon: 'mdi-shield-outline' },
  { label: 'Leeds United', path: '/leeds', icon: 'mdi-shield-outline' },
  { label: 'Aston Villa', path: '/aston-villa', icon: 'mdi-shield-outline' },
  { label: 'Brentford', path: '/brentford', icon: 'mdi-shield-outline' },
  { label: 'Chelsea', path: '/chelsea', icon: 'mdi-shield-outline' }
]
