export const navItems = [
  { header: 'Charts' },
  { label: 'All-Time Table', path: '/all-time-table', icon: 'mdi-table-large' },
  { label: 'Most Wins', path: '/most-wins', icon: 'mdi-chart-bar' },
  { label: 'Data Quality', path: '/data-quality', icon: 'mdi-shield-check' },
  { label: 'Attendances', path: '/attendances', icon: 'mdi-stadium' },
  { label: 'Five-Game Streaks', path: '/five-game-streaks', icon: 'mdi-run-fast' },
  { label: 'Big Win Streaks', path: '/big-win-streaks', icon: 'mdi-format-list-numbered' },
  { label: 'Longest Gap Between Wins', path: '/longest-winless-gaps', icon: 'mdi-timer-sand' },
  { label: 'Most Chaotic Matches', path: '/most-chaotic-matches', icon: 'mdi-fire' },
  { label: 'One-Nil Wins', path: '/one-nil-wins', icon: 'mdi-numeric-1-box-outline' },
  { label: 'Longest No-Win Streaks After HT Lead', path: '/ht-lead-no-win-streaks', icon: 'mdi-flag-checkered' },
  { label: 'Comeback Kings', path: '/comeback-kings', icon: 'mdi-trophy-outline' },
  { label: 'Most Comebacks in a Season', path: '/most-comebacks', icon: 'mdi-trophy-variant-outline' },
  { label: 'Most Manager Wins', path: '/manager-wins', icon: 'mdi-whistle-outline' },
  { label: 'Manager Timeline', path: '/manager-timeline', icon: 'mdi-chart-gantt' },

  { header: 'By manager' },
  { label: 'Arsène Wenger', path: '/wenger', icon: 'mdi-account-tie-outline' },
  { label: 'Alex Ferguson', path: '/ferguson', icon: 'mdi-account-tie-outline' },
  { label: 'David Moyes', path: '/moyes', icon: 'mdi-account-tie-outline' },
  { label: 'Pep Guardiola', path: '/guardiola', icon: 'mdi-account-tie-outline' },
  { label: 'Harry Redknapp', path: '/redknapp', icon: 'mdi-account-tie-outline' },
  { label: 'José Mourinho', path: '/mourinho', icon: 'mdi-account-tie-outline' },
  { label: 'Jürgen Klopp', path: '/klopp', icon: 'mdi-account-tie-outline' },
  { label: 'Sam Allardyce', path: '/allardyce', icon: 'mdi-account-tie-outline' },
  { label: 'Rafael Benítez', path: '/benitez', icon: 'mdi-account-tie-outline' },
  { label: 'Mark Hughes', path: '/hughes', icon: 'mdi-account-tie-outline' },
  { label: 'Mauricio Pochettino', path: '/pochettino', icon: 'mdi-account-tie-outline' },
  { label: 'Mikel Arteta', path: '/arteta', icon: 'mdi-account-tie-outline' },
  { label: 'Eddie Howe', path: '/howe', icon: 'mdi-account-tie-outline' },
  { label: 'Brendan Rodgers', path: '/rodgers', icon: 'mdi-account-tie-outline' },
  { label: 'Roy Hodgson', path: '/hodgson', icon: 'mdi-account-tie-outline' },
  { label: 'Steve Bruce', path: '/bruce', icon: 'mdi-account-tie-outline' },
  { label: "Martin O'Neill", path: '/o-neill', icon: 'mdi-account-tie-outline' },
  { label: 'Kevin Keegan', path: '/keegan', icon: 'mdi-account-tie-outline' },
  { label: 'Kenny Dalglish', path: '/dalglish', icon: 'mdi-account-tie-outline' },
  { label: "David O'Leary", path: '/o-leary', icon: 'mdi-account-tie-outline' },

  { header: 'By team' },
  { label: 'Arsenal', path: '/arsenal', icon: 'mdi-shield-outline' },
  { label: 'Manchester United', path: '/manchester-united', icon: 'mdi-shield-outline' },
  { label: 'Liverpool', path: '/liverpool', icon: 'mdi-shield-outline' },
  { label: 'Tottenham Hotspur', path: '/tottenham', icon: 'mdi-shield-outline' },
  { label: 'West Ham United', path: '/west-ham', icon: 'mdi-shield-outline' },
  { label: 'Manchester City', path: '/manchester-city', icon: 'mdi-shield-outline' },
  { label: 'Newcastle United', path: '/newcastle', icon: 'mdi-shield-outline' },
  { label: 'Sunderland', path: '/sunderland', icon: 'mdi-shield-outline' },
  { label: 'Leeds United', path: '/leeds', icon: 'mdi-shield-outline' },
  { label: 'Aston Villa', path: '/aston-villa', icon: 'mdi-shield-outline' },
  { label: 'Brentford', path: '/brentford', icon: 'mdi-shield-outline' },
  { label: 'Chelsea', path: '/chelsea', icon: 'mdi-shield-outline' },

  { header: 'By season' },
  { label: '1992-93 Season', path: '/epl-1992-93-season-stats', icon: 'mdi-calendar' },
  { label: '1993-94 Season', path: '/epl-1993-94-season-stats', icon: 'mdi-calendar' },
  { label: '1994-95 Season', path: '/epl-1994-95-season-stats', icon: 'mdi-calendar' },
  { label: '1995-96 Season', path: '/epl-1995-96-season-stats', icon: 'mdi-calendar' },
  { label: '1996-97 Season', path: '/epl-1996-97-season-stats', icon: 'mdi-calendar' },
  { label: '1997-98 Season', path: '/epl-1997-98-season-stats', icon: 'mdi-calendar' },
  { label: '1998-99 Season', path: '/epl-1998-99-season-stats', icon: 'mdi-calendar' },
  { label: '1999-00 Season', path: '/epl-1999-00-season-stats', icon: 'mdi-calendar' },
  { label: '2000-01 Season', path: '/epl-2000-01-season-stats', icon: 'mdi-calendar' },
  { label: '2001-02 Season', path: '/epl-2001-02-season-stats', icon: 'mdi-calendar' },
  { label: '2002-03 Season', path: '/epl-2002-03-season-stats', icon: 'mdi-calendar' },
  { label: '2003-04 Season', path: '/epl-2003-04-season-stats', icon: 'mdi-calendar' },
  { label: '2004-05 Season', path: '/epl-2004-05-season-stats', icon: 'mdi-calendar' },
  { label: '2005-06 Season', path: '/epl-2005-06-season-stats', icon: 'mdi-calendar' },
  { label: '2006-07 Season', path: '/epl-2006-07-season-stats', icon: 'mdi-calendar' },
  { label: '2007-08 Season', path: '/epl-2007-08-season-stats', icon: 'mdi-calendar' },
  { label: '2008-09 Season', path: '/epl-2008-09-season-stats', icon: 'mdi-calendar' },
  { label: '2009-10 Season', path: '/epl-2009-10-season-stats', icon: 'mdi-calendar' },
  { label: '2010-11 Season', path: '/epl-2010-11-season-stats', icon: 'mdi-calendar' },
  { label: '2011-12 Season', path: '/epl-2011-12-season-stats', icon: 'mdi-calendar' },
  { label: '2012-13 Season', path: '/epl-2012-13-season-stats', icon: 'mdi-calendar' },
  { label: '2013-14 Season', path: '/epl-2013-14-season-stats', icon: 'mdi-calendar' },
  { label: '2014-15 Season', path: '/epl-2014-15-season-stats', icon: 'mdi-calendar' },
  { label: '2015-16 Season', path: '/epl-2015-16-season-stats', icon: 'mdi-calendar' },
  { label: '2016-17 Season', path: '/epl-2016-17-season-stats', icon: 'mdi-calendar' },
  { label: '2017-18 Season', path: '/epl-2017-18-season-stats', icon: 'mdi-calendar' },
  { label: '2018-19 Season', path: '/epl-2018-19-season-stats', icon: 'mdi-calendar' },
  { label: '2019-20 Season', path: '/epl-2019-20-season-stats', icon: 'mdi-calendar' },
  { label: '2020-21 Season', path: '/epl-2020-21-season-stats', icon: 'mdi-calendar' },
  { label: '2021-22 Season', path: '/epl-2021-22-season-stats', icon: 'mdi-calendar' },
  { label: '2022-23 Season', path: '/epl-2022-23-season-stats', icon: 'mdi-calendar' },
  { label: '2023-24 Season', path: '/epl-2023-24-season-stats', icon: 'mdi-calendar' },
  { label: '2024-25 Season', path: '/epl-2024-25-season-stats', icon: 'mdi-calendar' },
  { label: '2025-26 Season', path: '/epl-2025-26-season-stats', icon: 'mdi-calendar' }
]
